name: ropu
base: core18
version: '0.1' 
summary: Client for Ropu group PTT system
description: |
  Ropu is a group PTT (Push to Talk) application.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

slots:
  # for GtkApplication registration
  sharp:
    interface: dbus
    bus: session
    name: org.gnome.ropu

apps:
  ropu:
    command: bin/desktop-launch $SNAP/ClientUI
    plugs:
      - alsa
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - gsettings

parts:
  ropu:
    # See 'snapcraft plugins'
    after: [desktop-gnome-platform]
    source: ClientUI/Install
    source-type: local
    plugin: dump
    stage-packages:
      - libasn1-8-heimdal
      - libcurl4
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libwind0-heimdal
      - libgtk3.0-cil
      - libasound2
      - libopus0
      - libortp9



  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: gtk

    plugin: make
    build-packages:
    - build-essential
    - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

plugs:
  gnome-3-28-1804:
    default-provider: gnome-3-28-1804:gnome-3-28-1804
    interface: content
    target: $SNAP/gnome-platform
  gtk-3-themes:
    default-provider: gtk-common-themes:gtk-3-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    default-provider: gtk-common-themes:icon-themes
    interface: content
    target: $SNAP/data-dir/icons
  sound-themes:
    default-provider: gtk-common-themes:sounds-themes
    interface: content
    target: $SNAP/data-dir/sounds

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa