name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore ropu.sln
    - name: Build
      run: dotnet build ropu.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ropu.sln --no-restore --verbosity normal

  Android:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore RopuForms.sln
        cd RopuForms.Android
        msbuild RopuForms.Android.csproj /verbosity:normal /t:Rebuild /t:SignAndroidPackage /p:Configuration=Release

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: RopuForms.Android/bin/Release/org.ropu.forms-Signed.apk
